# Generated by Django 4.1 on 2022-09-12 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('username', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
                ('bio', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(null=True)),
                ('license', models.CharField(max_length=12, null=True)),
                ('contact_no', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.TextField(null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('adhar_no', models.CharField(max_length=16, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('word_id', models.IntegerField()),
                ('room_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAX_BED', models.IntegerField()),
                ('active_bed', models.IntegerField()),
            ],
        ),
    ]
