# Generated by Django 4.1 on 2022-09-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nurse', max_length=20)),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
                ('bio', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.TextField(null=True)),
                ('license', models.CharField(max_length=12, null=True)),
                ('contact_no', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
