# Generated by Django 4.1 on 2022-09-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='allocated_word',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='last_update_date',
            field=models.DateField(null=True),
        ),
    ]
