# Generated by Django 4.1 on 2022-09-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_nurse_allocated_word_alter_nurse_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='queue_order',
            field=models.IntegerField(default=0),
        ),
    ]
