# Generated by Django 4.1 on 2022-09-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_nurse_queue_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='queue_order',
            field=models.IntegerField(default=-1),
        ),
    ]
