# Generated by Django 4.1 on 2022-09-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_nurse_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='contact_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='license',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
